### ISSUE TITLE
Remove the version/ascii-art note

### ISSUE THREAD

**Issue by PawelLipski** [antkorwin/better-strings#3]
Thanks for providing this tool! It's so weird that it isn't super-popular/a _de facto_ standard yet given how useful it is!

My first impression (using version 0.2 under gradle: `annotationProcessor 'com.antkorwin:better-strings:0.2'`): this note isn't necessary... and also the version number is incorrect ;/

```
Note: 
  ___  ____ ___ ___ ____ ____    ____ ___ ____ _ _  _ ____ ____ 
  |__] |___  |   |  |___ |__/    [__   |  |__/ | |\ | | __ [__  
  |__] |___  |   |  |___ |  \    ___]  |  |  \ | | \| |__] ___] 
     v0.1 String Interpolation Java Plugin, by Anatoliy Korovin  
```

**Comment by antkorwin** [comment]
Hi, @PawelLipski !
Thanks for the kind words.

I will remove this banner, by the way sometimes this message is wrong formatted in the IntelliJ idea, I think the reason is a not monospaced font.

**Comment by PawelLipski** [comment]
Hi @antkorwin ... any progress on this one? :)

**Comment by antkorwin** [comment]
Hi @PawelLipski 

I removed the banner, made a new release ([release 0.3](https://github.com/antkorwin/better-strings/releases/tag/v0.3)) and published it in the maven central.

**Comment by PawelLipski** [comment]
Thanks @antkorwin, I just picked it up in my project... if you could remove `Note: v0.3 String Interpolation Java Plugin, by Anatoliy Korovin` as well :)
